spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway
    username: root
    password: kEIOQBrlkEUXcvOcCsVyFTclujUfeyZO
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30  # プールサイズを本番用に増加
      minimum-idle: 10        # 最小アイドル接続数
      connection-timeout: 30000  # 接続タイムアウト（ミリ秒）
      idle-timeout: 600000      # アイドルタイムアウト（ミリ秒）
      max-lifetime: 1800000     # 最大ライフタイム（ミリ秒）
      keepalive-time: 30000     # 接続の保持時間（ミリ秒）

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none  # 本番環境では自動DDLを無効に
    show-sql: false   # 本番環境ではSQLの表示を無効
    open-in-view: false  # パフォーマンス向上のため false に設定
    properties:
      hibernate:
        format_sql: false  # フォーマットされたSQLの表示を無効

server:
  servlet:
    session:
      timeout: 30m  # セッションタイムアウトを30分に設定（本番環境では適切に調整）
      cookie:
        max-age: 1800  # クッキーの有効期限を30分に設定（本番環境では適切に調整）

logging:
  level:
    org.hibernate.SQL: WARN  # SQLログの出力を抑制
    org.hibernate.type.descriptor.sql.BasicBinder: WARN  # SQLバインディングのログを抑制
    # ログの詳細レベルを調整し、過度な出力を抑える
